[versions]
activityCompose = "1.11.0"
agp = "8.13.0"
androidXCoreKtx = "1.17.0"
androidXTest = "1.6.0"
androidXTestJUnit = "1.3.0"
androidXTestOrchestrator = "1.6.1"
androidXTestRunner = "1.7.0"
androidXTestRules = "1.7.0"
appcompat = "1.7.1"
composeBom = "2025.10.01"
composable-preview-scanner = "0.7.1"
compose-lint-checks = "1.4.2"
espressoCore = "3.7.0"
google-play-review= "2.0.2"
imposter = "4.6.2" # https://github.com/imposter-project/imposter-jvm-engine/releases/tag/v4.6.2
junit = "6.0.1"
junit4 = "4.13.2"
konsist = "0.17.3"
kotlin = "2.2.21"
kotlinx-collections-immutable = "0.4.0"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization-json = "1.9.0"
ksp = "2.3.1"
lifecycle = "2.9.4"
metro = "0.7.3"
mockito = "6.1.0"
molecule = "2.2.0"
navigation = "2.9.5"
paparazzi = "2.0.0-alpha02"
robolectric = "4.15.1"
testparameterinjector = "1.19"
turbine = "1.2.1"
uk-gov-logging = "0.32.2" # https://github.com/orgs/govuk-one-login/packages?repo_name=mobile-android-logging
uk-gov-networking = "0.7.2"
uk-gov-ui = "9.0.0"
gov-uk-idcheck = "0.30.0" # https://github.com/govuk-one-login/mobile-id-check-android-sdk/releases

[libraries]
android-build-tool = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidXCoreKtx" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidXTestJUnit" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-savedstate = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
androidx-test-core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "androidXTest" }
androidx-test-espresso-accessibility = { module = "androidx.test.espresso:espresso-accessibility", version.ref = "espressoCore" }
androidx-test-orchestrator = { group = "androidx.test", name = "orchestrator", version.ref = "androidXTestOrchestrator" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidXTestRules" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidXTestRunner" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
app-cash-molecule-runtime = { module = "app.cash.molecule:molecule-runtime", version.ref = "molecule" }
app-cash-paparazzi = { module = "app.cash.paparazzi:paparazzi", version.ref = "paparazzi" }
app-cash-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
com-lemonappdev-konsist = { module = "com.lemonappdev:konsist", version.ref = "konsist" }
com-slack-lint-compose = { module = "com.slack.lint.compose:compose-lint-checks", version.ref = "compose-lint-checks" }
composable-preview-scanner = { module = "io.github.sergio-sastre.ComposablePreviewScanner:android", version.ref = "composable-preview-scanner" }
google-play-review = { module = "com.google.android.play:review", version.ref = "google-play-review" }
google-play-review-kotlin = { module = "com.google.android.play:review-ktx", version.ref = "google-play-review" }
google-testparameterinjector = { module = "com.google.testparameterinjector:test-parameter-injector", version.ref = "testparameterinjector" }
imposter-config-parser = { group = "io.gatehill.imposter", name = "config-dynamic", version.ref = "imposter" }
imposter-main = { group = "io.gatehill.imposter", name = "distro-embedded", version.ref = "imposter" }
imposter-openapi-plugin = { group = "io.gatehill.imposter", name = "mock-openapi", version.ref = "imposter" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
ksp-gradle-plugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
metro-gradle-plugin = { module = "dev.zacsweers.metro:gradle-plugin", version.ref = "metro" }
metro-runtime = { module = "dev.zacsweers.metro:runtime", version.ref = "metro" }
org-junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
org-junit-junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
org-junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter" }
org-junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine" }
org-junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
org-junit-vintage = { group = "org.junit.vintage", name = "junit-vintage-engine" }
org-mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito" }
org-robolectric-robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
uk-gov-logging-api = { group = "uk.gov.logging", name = "logging-api", version.ref = "uk-gov-logging" }
uk-gov-logging-impl = { group = "uk.gov.logging", name = "logging-impl", version.ref = "uk-gov-logging" }
uk-gov-logging-testdouble = { group = "uk.gov.logging", name = "logging-testdouble", version.ref = "uk-gov-logging" }
uk-gov-networking = { group = "uk.gov.android", name = "network", version.ref = "uk-gov-networking" }
uk-gov-pipelines-plugins = { module = "uk.gov.pipelines:plugins" }
uk-gov-ui-components-v2 = { group = "uk.gov.android", name = "componentsv2", version.ref = "uk-gov-ui" }
uk-gov-ui-patterns = { group = "uk.gov.android", name = "patterns", version.ref = "uk-gov-ui" }
uk-gov-ui-theme = { group = "uk.gov.android", name = "theme", version.ref = "uk-gov-ui" }
uk-gov-idcheck-repositories-api = { module = "uk.gov.onelogin.idcheck:repositories-api", version.ref = "gov-uk-idcheck" }
uk-gov-idcheck-ui-presentation = { module = "uk.gov.onelogin.idcheck:ui-presentation", version.ref = "gov-uk-idcheck" }
uk-gov-idcheck-sdk = { module = "uk.gov.onelogin.idcheck:sdk", version.ref = "gov-uk-idcheck" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
app-cash-paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
metro = { id = "dev.zacsweers.metro", version.ref = "metro" }

[bundles]
uk-gov-ui = ["uk-gov-ui-components-v2", "uk-gov-ui-theme", "uk-gov-ui-patterns"]
imposter = ["imposter-config-parser", "imposter-main", "imposter-openapi-plugin"]
