# Dependencies in this version catalog are used in the test wrapper app but shouldn't
# find their way into production CRI Orchestrator SDK builds.

[versions]
dagger = "2.57"
firebase-bom = "34.1.0" # https://firebase.google.com/support/release-notes/android
firebase-crashlytics-gradle = "3.0.6" # https://firebase.google.com/support/release-notes/android
google-services = "4.4.3" # https://developers.google.com/android/guides/releases

[libraries]
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger" }
uk-gov-idcheck-hilt-config = { module = "uk.gov.onelogin.idcheck:hilt-config" }

[plugins]
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-gradle" }
hilt-gradle = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
